#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Stigey `reservation/` → production Supabase project + Vercel deploy.
# ──────────────────────────────────────────────────────────────────────────

RESERVATION_DIR="/home/richard/Projects/Stigey/reservation"
ENV_FILE="$RESERVATION_DIR/.env.production.local"   # gitignored (.env* pattern)

TOTAL_STAGES=10

banner "Stigey reservation/ → production (Supabase + Vercel)"

# ── 1. Supabase: create the prod project ───────────────────────────────────
stage "Supabase: create production project"
say "This is a separate project from your local dev Supabase (127.0.0.1) —"
say "it needs its own project, DB password, and API keys."
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project'. Pick an org, name it e.g. 'stigey-prod', region"
step "close to France (eu-west-3 / Paris if offered, else eu-central/eu-west)."
step "Set a strong DB password when prompted — you'll paste it below too."
pause "Project created and finished provisioning?"
step "Open the new project → Settings → General → copy the 'Reference ID'."
ask SUPABASE_PROJECT_REF "Paste the project reference ID:"
ask_secret SUPABASE_DB_PASSWORD "Paste the DB password you just set:"
note "DB password is only used locally to link the CLI — not sent anywhere else."

# ── 2. Supabase: push the schema migrations ─────────────────────────────────
stage "Supabase: run migrations"
say "Applying $RESERVATION_DIR/supabase/migrations/ to the new project."
if confirm "Run 'supabase link' + 'supabase db push' against $SUPABASE_PROJECT_REF now?"; then
  ( cd "$RESERVATION_DIR" \
    && SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx supabase link --project-ref "$SUPABASE_PROJECT_REF" \
    && SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" npx supabase db push --linked )
  printf '  %s✓ migrations pushed%s\n' "$GREEN" "$RESET"
else
  warn "skipped — run manually later: cd $RESERVATION_DIR && npx supabase link --project-ref $SUPABASE_PROJECT_REF && npx supabase db push --linked"
  SKIPPED+=("push migrations to $SUPABASE_PROJECT_REF")
fi

# ── 3. Supabase: capture API keys ───────────────────────────────────────────
stage "Supabase: API keys"
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/settings/api"
step "Copy 'Project URL'."
ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL:"
step "Copy the 'anon' / 'public' key."
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the anon key:"
step "Copy the 'service_role' key (click reveal — keep this one secret)."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service_role key:"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── 4. Supabase: load real business data (not the demo rows) ───────────────
stage "Supabase: load prestations / horaires / réglages"
say "supabase/prod-seed.sql has the real catalogue + hours + réglages, with the"
say "demo clients and the local-only auth user stripped out."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/sql/new"
step "Open $RESERVATION_DIR/supabase/prod-seed.sql in your editor, copy it all,"
step "paste into the SQL editor tab that just opened, click Run."
pause "Ran without errors?"

# ── 5. Domain ────────────────────────────────────────────────────────────
stage "Buy the domain"
open_url "https://vercel.com/domains"
step "Search for and buy the domain (e.g. stigey.fr). Vercel manages its DNS"
step "automatically once bought there — that's where you'll add records below."
ask APP_DOMAIN "Domain you bought (e.g. stigey.fr):"
note "If you bought it elsewhere instead, you'll add the same DNS records via"
note "that registrar's dashboard in the next two stages."

# ── 6. Email forwarding for the praticienne's inbox ─────────────────────────
stage "Email forwarding: praticienne@$APP_DOMAIN"
say "Free forwarding (praticienne@$APP_DOMAIN → her real inbox), no mailbox needed."
say "Doing this before creating her login, so the login email is one she can"
say "actually receive mail at."
open_url "https://improvmx.com/"
step "Sign up, add domain '$APP_DOMAIN'."
step "ImprovMX shows 2 DNS records (MX + a TXT/SPF record)."
open_url "https://vercel.com/dashboard"
step "Go to your account → Domains → $APP_DOMAIN → DNS Records, add both records"
step "ImprovMX gave you."
ask FORWARD_TO_EMAIL "Her real inbox to forward to:"
step "Back in ImprovMX, add an alias: praticienne -> $FORWARD_TO_EMAIL"
pause "Alias saved and DNS records added?"

# ── 7. Supabase: create the praticienne's real login ────────────────────────
stage "Supabase: praticienne account"
warn "Do NOT reuse the dev password from supabase/seed.sql (stigey-dev-2026)."
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/auth/users"
step "Click 'Add user' → 'Create new user'."
ask PRATICIENNE_EMAIL "Her login email [praticienne@$APP_DOMAIN]:"
PRATICIENNE_EMAIL="${PRATICIENNE_EMAIL:-praticienne@$APP_DOMAIN}"
step "Set 'Auto Confirm User' to on, and set a real password (share it with"
step "her out of band — don't paste it back here)."
pause "Account created and email confirmed?"
write_env PRATICIENNE_EMAIL "$PRATICIENNE_EMAIL"
ask PRATICIENNE_NOM "Her display name for calendar invites [Sonia Bah]:"
PRATICIENNE_NOM="${PRATICIENNE_NOM:-Sonia Bah}"
write_env PRATICIENNE_NOM "$PRATICIENNE_NOM"

# ── 8. Resend (transactional email) ─────────────────────────────────────────
stage "Resend: domain + API key"
open_url "https://resend.com/domains"
step "Add domain '$APP_DOMAIN' (sign in / sign up first if needed)."
step "Resend shows DNS records (DKIM/SPF, sometimes DMARC)."
step "Add them the same way, in Vercel → Domains → $APP_DOMAIN → DNS Records."
pause "Records added? (Resend verifies them shortly after — a few minutes, occasionally longer)"
open_url "https://resend.com/api-keys"
step "Create an API key (Sending access is enough)."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"
RESEND_FROM_EMAIL="Stigey <reservations@$APP_DOMAIN>"
write_env RESEND_FROM_EMAIL "$RESEND_FROM_EMAIL"
note "RESEND_FROM_EMAIL set to: $RESEND_FROM_EMAIL"

# ── 9. Cron secret ───────────────────────────────────────────────────────
stage "Cron secret"
say "Vercel Cron sends this as 'Authorization: Bearer <secret>' when it hits"
say "/api/cron/rappels — generating one now, no dashboard needed."
CRON_SECRET=$(openssl rand -hex 20)
write_env CRON_SECRET "$CRON_SECRET"
note "generated: $CRON_SECRET"

# ── 10. Vercel: link, push env vars, deploy ─────────────────────────────────
stage "Vercel: link + env vars + deploy"
say "Logging in opens a browser tab to confirm."
( cd "$RESERVATION_DIR" && npx vercel login )
say "Linking — when asked, link to a NEW project, keep the default settings."
( cd "$RESERVATION_DIR" && npx vercel link )
say "Pushing production env vars…"
for key in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY \
           SUPABASE_SERVICE_ROLE_KEY RESEND_API_KEY RESEND_FROM_EMAIL \
           PRATICIENNE_EMAIL PRATICIENNE_NOM CRON_SECRET; do
  val=$(_existing "$key" || true)
  [[ -z "$val" ]] && { warn "no value for $key, skipping"; SKIPPED+=("Vercel env $key"); continue; }
  ( cd "$RESERVATION_DIR" && { npx vercel env rm "$key" production --yes >/dev/null 2>&1 || true; }
    printf '%s' "$val" | npx vercel env add "$key" production >/dev/null ) \
    && printf '  %s✓ set%s Vercel env %s (production)\n' "$GREEN" "$RESET" "$key" \
    || { warn "failed to set Vercel env $key"; SKIPPED+=("Vercel env $key"); }
done
note "In Vercel Project Settings → General, confirm 'Root Directory' = reservation"
note "(vercel link from this subfolder usually sets it, but worth checking)."
if confirm "Deploy to production now (npx vercel --prod)?"; then
  ( cd "$RESERVATION_DIR" && npx vercel --prod )
else
  SKIPPED+=("deploy: cd $RESERVATION_DIR && npx vercel --prod")
fi
note "Cron: vercel.json already schedules /api/cron/rappels daily at 08:00 UTC —"
note "check Vercel → your project → Cron Jobs after the first deploy to confirm"
note "it registered, and add the custom domain ($APP_DOMAIN) under Domains."
# ──────────────────────────────────────────────────────────────────────────

finish
